#include "relay.h"

void Relay_GPIO_Init(void) {
    RCC->AHB1ENR |= RELAY1_RCC_AHB1ENR | RELAY2_RCC_AHB1ENR;
    RELAY1_GPIO_PORT->MODER &= ~(3U << (RELAY1_PIN * 2));
    RELAY1_GPIO_PORT->MODER |= (1U << (RELAY1_PIN * 2));
    RELAY2_GPIO_PORT->MODER &= ~(3U << (RELAY2_PIN * 2));
    RELAY2_GPIO_PORT->MODER |= (1U << (RELAY2_PIN * 2));
    RELAY1_GPIO_PORT->OTYPER &= ~(1U << RELAY1_PIN);
    RELAY2_GPIO_PORT->OTYPER &= ~(1U << RELAY2_PIN);
    RELAY1_GPIO_PORT->PUPDR &= ~(3U << (RELAY1_PIN * 2));
    RELAY2_GPIO_PORT->PUPDR &= ~(3U << (RELAY2_PIN * 2));
    RELAY1_GPIO_PORT->OSPEEDR &= ~(3U << (RELAY1_PIN * 2));
    RELAY2_GPIO_PORT->OSPEEDR &= ~(3U << (RELAY2_PIN * 2));
    RELAY1_GPIO_PORT->ODR &= ~(1U << RELAY1_PIN);
    RELAY2_GPIO_PORT->ODR &= ~(1U << RELAY2_PIN);
}
